var Games =
[
  {id: 0, name: "Battlefield 1", desc: "Battlefield 1 is a first-person shooter video game developed by EA DICE and published by Electronic Arts. It is the fifteenth installment in the Battlefield series, and the first main entry in the series since Battlefield 4.", img: "./images/Battlefield1.jpg", link: "https://www.battlefield.com/games/battlefield-1", year: "2016", commentsArray: []},
  {id: 1, name: "Bloodborne", desc: "Bloodborne is an action role-playing video game developed by FromSoftware and published by Sony Computer Entertainment.", img: "./images/bloodborne.jpg", link: "http://www.fromsoftware.jp/pc_en/product/detail_92.html", year: "2015", commentsArray: []},
  {id: 2, name: "Dark Souls", desc: "Dark Souls is an action role-playing video game developed by FromSoftware and published by Namco Bandai Games for PlayStation 3, Xbox 360, and Microsoft Windows.", img: "./images/darksouls.jpg", link: "http://www.fromsoftware.jp/pc_en/product/detail_85.html", year: "2011", commentsArray: []},
  {id: 3, name: "Dark Souls 2", desc: "Dark Souls 2 is an action role-playing video game developed by FromSoftware and published by Bandai Namco Games. The third game in the Souls series, Dark Souls II was released for Microsoft Windows, PlayStation 3, and Xbox 360.", img: "./images/dark-souls-2.jpg", link: "http://www.fromsoftware.jp/pc_en/product/detail_91.html", year: "2014", commentsArray: []},
  {id: 4, name: "Dark Souls 3", desc: "Dark Souls 3 is an action role-playing video game developed by FromSoftware and published by Bandai Namco Entertainment for PlayStation 4, Xbox One, and Microsoft Windows.", img: "./images/Dark_souls3.jpg", link: "http://www.darksouls3.com/us/", year: "2016", commentsArray: []},
  {id: 5, name: "Dishonored", desc: "Dishonored is a 2012 stealth action-adventure video game developed by Arkane Studios and published by Bethesda Softworks. It was released worldwide in October 2012 for Microsoft Windows, PlayStation 3, and Xbox 360.", img: "./images/Dishonored.png", link: "https://en.wikipedia.org/wiki/Dishonored", year: "2012", commentsArray: []},
  {id: 6, name: "Dishonored 2", desc: "Dishonored 2 is an action-adventure stealth video game developed by Arkane Studios and published by Bethesda Softworks. The sequel to 2012's Dishonored, the game was released for Microsoft Windows, PlayStation 4, and Xbox One on November 11, 2016.", img: "./images/Dishonored_2.jpg", link: "https://dishonored.bethesda.net/en", year: "2016", commentsArray: []},
  {id: 7, name: "Grand Theft Auto 5", desc: "Grand Theft Auto 5 is an open world action-adventure video game developed by Rockstar North and published by Rockstar Games. It was released on 17 September 2013 for the PlayStation 3 and Xbox 360.", img: "./images/Grand-Theft-Auto-5.jpg", link: "http://www.rockstargames.com/V/", year: "2013", commentsArray: []},
  {id: 8, name: "Overwatch", desc: "Overwatch is a team-based multiplayer first-person shooter video game developed and published by Blizzard Entertainment.", img: "./images/overwatch.jpg", link: "https://playoverwatch.com/en-us/", year: "2016", commentsArray: []},
  {id: 9, name: "Rise of the Tomb Raider", desc: "Rise of the Tomb Raider is an action-adventure video game developed by Crystal Dynamics and published by Square Enix.", img: "./images/rise-of-the-tomb-raider.jpg", link: "https://www.tombraider.com/en-us", year: "2015", commentsArray: []},
  {id: 10, name: "Star Wars: Battlefront", desc: "Star Wars: Battlefront is an action shooter video game developed by EA DICE, with additional work from Criterion Games,", img: "./images/star-wars-battlefront.jpg", link: "http://starwars.ea.com/starwars/battlefront", year: "2015", commentsArray: []},
  {id: 11, name: "Titanfall 2", desc: "Titanfall 2 is a first-person shooter video game developed by Respawn Entertainment and published by Electronic Arts.", img: "./images/Titanfall2.jpg", link: "https://www.titanfall.com/en_us/", year: "2016", commentsArray: []},
  {id: 12, name: "Tomb Raider", desc: "Tomb Raider is an action-adventure video game developed by Crystal Dynamics and published by Square Enix.", img: "./images/tomb-raider.jpg", link: "https://www.tombraider.com/en-us", year: "2013", commentsArray: []},
  {id: 13, name: "Watchdogs", desc: "Watchdogs is an open world action-adventure third-person shooter video game developed and published by Ubisoft.", img: "./images/watchdogs.jpg", link: "https://www.ubisoft.com/en-GB/game/watch-dogs", year: "2014", commentsArray: []},
  {id: 14, name: "Watchdogs 2", desc: "Watchdogs 2 is an open world action-adventure video game developed by Ubisoft Montreal and published by Ubisoft.", img: "./images/WatchDogs2.jpg", link: "watchdogs.ubisoft.com/watchdogs/en-us/home/", year: "2016", commentsArray: []},
  {id: 15, name: "Witcher 3: Wild Hunt", desc: "Witcher 3: Wild Hunt is an open world action role-playing video game developed by CD Projekt RED.", img: "./images/Witcher_3.jpg", link: "www.thewitcher.com/", year: "2015", commentsArray: []}
  
]

export default Games;
